on:
  push:
    branches:
      - master      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_NAME2 }} --password ${{ secrets.DOCKER_PASS }}
      - name: " building docker "
        run: docker build -t ${{secrets.DOCKER_NAME2}}/javat:dev .
      - name: " pushing to docker hub "
        run: docker push ${{secrets.DOCKER_NAME2}}/javat:dev
